FROM archlinux:latest

ENV ANSIBLE_USER=ansible SUDO_GROUP=wheel

RUN pacman -Syu --noconfirm python sudo && \
    groupadd -r ${ANSIBLE_USER} && \
    useradd -m -g ${ANSIBLE_USER} ${ANSIBLE_USER} && \
    echo "${ANSIBLE_USER} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

USER $ANSIBLE_USER
