---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  ansible-lint .
  find . -type f -name "*.py" ! -path '*/.py_venv/*' | xargs pylint
platforms:
  - name: archlinuxe
    hostname: archlinux
    image: archlinux_molecule:latest
    dockerfile: Dockerfile.archlinuxe.j2
  - name: debian
    hostname: debian
    image: debian_molecule:latest
    dockerfile: Dockerfile.debian.j2
provisioner:
  name: ansible
  options:
    v: True
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python
        ansible_user: ansible
verifier:
  name: ansible
